### ISSUE TITLE
panic: run time error

### ISSUE THREAD

**Issue by nandokferrari** [AssemblyAI/assemblyai-cli#80]
**Describe the bug**
I tried to run the following command:

`assemblyai transcribe https://www.youtube.com/watch\?v\=xUqN2kj6Tt0 --auto_highlights --entity_detection`

to transcribe a brazilian portuguese video, but got the output:

```
Transcribing YouTube video...
Downloading video:  5.77 MB / 5.77 MB  100.00% 1s                                                         
Uploading file to our servers:  5.77 MB / 5.77 MB  100.00% 20s                                            
Transcribing file with id r2saqo91d8-0cc5-4b7e-9256-1d19edcd7b35
Transcript


Highlights
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10450eed4]

goroutine 1 [running]:
github.com/AssemblyAI/assemblyai-cli/utils.getFormattedOutput({0x140000e3eb0, 0x140000275e0, 0x0, 0x0, 0x140000e3ee0, 0x140000275f7, 0x140000275f0, 0x0, {0x0, 0x0}, ...}, ...)
	/home/runner/work/assemblyai-cli/assemblyai-cli/utils/transcribe.go:306 +0x194
github.com/AssemblyAI/assemblyai-cli/utils.PollTranscription({0x140000ce4e0, 0x26}, {0x80?, 0x5?})
	/home/runner/work/assemblyai-cli/assemblyai-cli/utils/transcribe.go:280 +0x2d0
github.com/AssemblyAI/assemblyai-cli/utils.Transcribe({{0x1400002bd10, 0x46}, 0x0, 0x1, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
	/home/runner/work/assemblyai-cli/assemblyai-cli/utils/transcribe.go:144 +0x588
github.com/AssemblyAI/assemblyai-cli/cmd.glob..func4(0x104985960?, {0x14000214ba0?, 0x3?, 0x3?})
	/home/runner/work/assemblyai-cli/assemblyai-cli/cmd/transcribe.go:259 +0xafc
github.com/spf13/cobra.(*Command).execute(0x104985960, {0x14000214b70, 0x3, 0x3})
	/home/runner/work/assemblyai-cli/assemblyai-cli/vendor/github.com/spf13/cobra/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x1049856e0)
	/home/runner/work/assemblyai-cli/assemblyai-cli/vendor/github.com/spf13/cobra/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/assemblyai-cli/assemblyai-cli/vendor/github.com/spf13/cobra/command.go:918
github.com/AssemblyAI/assemblyai-cli/cmd.Execute()
	/home/runner/work/assemblyai-cli/assemblyai-cli/cmd/root.go:42 +0xa8
main.main()
	/home/runner/work/assemblyai-cli/assemblyai-cli/main.go:11 +0x1c
```

Not sure why it happened, I tried with different brazilian videos, and same thing. Maybe it is something about the language.
When trying with ensligh videos, everything works fine.

**Comment by fcastillo90** [comment]
Hey @nandokferrari, thanks for the report! Just created a PR for this fix, although please visit our documentation page regarding languages [here](https://www.assemblyai.com/docs#supported-languages) to see which features are supported, and use `-g pt` flag on our CLI for Portuguese
