### ISSUE TITLE
panic: runtime error: index out of range [7192] with length 7192

### ISSUE THREAD

**Issue by BuzzTea89** [AssemblyAI/assemblyai-cli#92]
I don't know, if I can post it here.
It's not a bug, I think.

But I got the following error message. What does it mean? It's only when i try one specific mp3-file.
Other files worked well without any issue.

Can somebody help me?

`panic: runtime error: index out of range [7192] with length 7192

goroutine 1 [running]:
github.com/AssemblyAI/assemblyai-cli/utils.GetSentenceTimestamps({0xc00031c000?, 0x111, 0x1051601?}, {0xc00086c000, 0x1c18, 0xc0001fb4d8?})
        /home/runner/work/assemblyai-cli/assemblyai-cli/utils/utils.go:274 +0x71a
github.com/AssemblyAI/assemblyai-cli/utils.textPrintFormatted({0xc0002d4000, 0xaaa6}, {0xc00086c000, 0x1c18, 0x1f9c})
        /home/runner/work/assemblyai-cli/assemblyai-cli/utils/transcribe.go:381 +0x13c
github.com/AssemblyAI/assemblyai-cli/utils.getFormattedOutput({0xc000088630, 0xc0002d0f78, 0x0, 0x0, 0xc000088660, 0xc0002d0f9c, 0xc0002d0f89, 0x0, {0x0, 0x0}, ...}, ...)
        /home/runner/work/assemblyai-cli/assemblyai-cli/utils/transcribe.go:337 +0xd3
github.com/AssemblyAI/assemblyai-cli/utils.PollTranscription({0xc0000c8b70, 0x26}, {0x80?, 0x5?, 0x0?})
        /home/runner/work/assemblyai-cli/assemblyai-cli/utils/transcribe.go:319 +0x428
github.com/AssemblyAI/assemblyai-cli/utils.Transcribe({{0xc000026190, 0x46}, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
        /home/runner/work/assemblyai-cli/assemblyai-cli/utils/transcribe.go:154 +0x672
github.com/AssemblyAI/assemblyai-cli/cmd.glob..func4(0x1058aa0?, {0xc00002c6f0?, 0x3?, 0x3?})
        /home/runner/work/assemblyai-cli/assemblyai-cli/cmd/transcribe.go:261 +0xdd0
github.com/spf13/cobra.(*Command).execute(0x1058aa0, {0xc00002c6c0, 0x3, 0x3})
        /home/runner/work/assemblyai-cli/assemblyai-cli/vendor/github.com/spf13/cobra/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x1058820)
        /home/runner/work/assemblyai-cli/assemblyai-cli/vendor/github.com/spf13/cobra/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/assemblyai-cli/assemblyai-cli/vendor/github.com/spf13/cobra/command.go:918
github.com/AssemblyAI/assemblyai-cli/cmd.Execute()
        /home/runner/work/assemblyai-cli/assemblyai-cli/cmd/root.go:42 +0x85
main.main()
        /home/runner/work/assemblyai-cli/assemblyai-cli/main.go:11 +0x17`

**Comment by BuzzTea89** [comment]
Ok thank you for your fast response!
